# Generated by Django 4.2 on 2023-04-07 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_rename_sale_percent_book_sales_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='BookAuthor',
        ),
    ]
